/*
* Generated file
*
* Generated from: yang module name: sfc-ovs-impl yang module local name: sfc-ovs-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jan 11 21:28:56 KST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_ovs.impl;
public class SfcOvsModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_ovs.impl.AbstractSfcOvsModuleFactory {

}
