/*
* Generated file
*
* Generated from: yang module name: sfc-provider-impl yang module local name: sfc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jan 11 21:22:02 KST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_provider.impl;
public class SfcProviderModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_provider.impl.AbstractSfcProviderModuleFactory {

}
